name: Build & Push FastAPI Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/build-push.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER/py-hello:latest
          docker build -t $IMAGE -f app/Dockerfile app
          docker push $IMAGE