name: CI
on: [push]

env:
  IMAGE_NAME: aw-bootcamp-app

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        id: tf
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: infra/terraform

      - name: Sync S3 and Invalidate CloudFront
        run: |
          BUCKET=$(terraform output -raw s3_bucket_name)
          DIST_ID=$(terraform output -raw cloudfront_distribution_id)
          aws s3 cp ../../index.html s3://$BUCKET/index.html
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
        working-directory: infra/terraform

  security-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
        working-directory: app

      # Paso 1: Ejecutar Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      # Paso 2: Ejecutar PHPStan
      - name: Install PHPStan
        run: |
          composer require --dev phpstan/phpstan
          vendor/bin/phpstan analyse index.php --level=7
        working-directory: app

      # Paso 3: Ejecutar SonarQube
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >-
            -Dsonar.organization=hugox2003
            -Dsonar.projectKey=HugoX2003_aw-devops-platform
            -Dsonar.exclusions=vendor/**,infra/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Paso 4: Subir DB Password a SSM Parameter Store
      - name: Store DB Password in SSM
        run: |
          aws ssm put-parameter --name /aw/bootcamp/db/password --value "supersecret" --type SecureString --overwrite

      # Paso 5: Recuperar el parámetro DB Password desde SSM
      - name: Retrieve DB password from SSM
        run: |
          DB_PASS=$(aws ssm get-parameter --name /aw/bootcamp/db/password --with-decryption --query "Parameter.Value" --output text)
          
          echo "DB_PASSWORD=$DB_PASS" >> $GITHUB_ENV
          echo "La variable ha sido inyectada correctamente en el entorno de la aplicación."

      - name: Verify Injection
        run: |
          if [ -z "$DB_PASSWORD" ]; then
            echo "Error: Variable no inyectada"
            exit 1
          else
            echo "Verificación Exitosa: La App detecta la variable DB_PASSWORD proveniente de SSM"
          fi